$(document).ready(function(){
    $("#signup-form").validate({
        rules:{
            fName:{
                required:true
            },
            sName:{
                required:true
            },
            emailOrPhone:{
                required:true,
                email:true
            }
        }
    })
})